// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZWU4giv9EJ_OoZqNYqfwu_kHGqcEMBM',
    appId: '1:513609381550:android:aa80e5f7f97b9d22f79f3f',
    messagingSenderId: '513609381550',
    projectId: 'instagram-ui-pdp',
    databaseURL: 'https://instagram-ui-pdp-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-ui-pdp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHG8Su-JKj8ou6y3S-Pwuea5h46W2Cqc',
    appId: '1:513609381550:ios:687462924f5f4e55f79f3f',
    messagingSenderId: '513609381550',
    projectId: 'instagram-ui-pdp',
    databaseURL: 'https://instagram-ui-pdp-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-ui-pdp.appspot.com',
    iosBundleId: 'com.example.maydonAdminPanel',
  );
}
